export const FETCH_PROFILE = "BNB/Profile/FETCH_PROFILE";
export const FETCH_PROFILE_SUCCESS = "BNB/Profile/FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAILURE = "BNB/Profile/FETCH_PROFILE_FAILURE";
